-- local on_attach = function(_, bufnr)
--   -- format on save
--   vim.api.nvim_create_autocmd('BufWritePre', {
--     buffer = bufnr,
--     callback = function()
--       vim.lsp.buf.format()
--     end
--   })
-- end
--
--
-- local capabilities = require('cmp_nvim_lsp').default_capabilities()
--
-- require("neodev").setup({})
--
-- local lsp_config = {
--   capabilities = capabilities,
--   group = vim.api.nvim_create_augroup('LspFormatting', { clear = true }),
--   on_attach = function(_, bufnr)
--     on_attach(_, bufnr)
--   end
-- }
--
-- require('mason-lspconfig').setup_handlers({
--   function(server_name)
--     require('lspconfig')[server_name].setup(lsp_config)
--   end,
--   tsserver = function()
--     require('typescript').setup({
--       server = vim.tbl_extend('force', lsp_config, {
--         on_attach = function(_, bufnr)
--           on_attach(_, bufnr)
--         end,
--         init_options = {
--           preferences = {
--             importModuleSpecifierPreference = 'project=relative',
--             jsxAttributeCompletionStyle = 'none'
--           }
--         }
--       })
--     })
--   end
-- })
--
vim.g.python3_host_prog = '/Users/koinworks/.pyenv/shims/python'
